### ISSUE TITLE
Could not inspect tasks for client [{id}]! Skipping ioprio optimisation.

### ISSUE THREAD

**Issue by telans** [FeralInteractive/gamemode#167]
**Describe the bug**

While running games via steam proton and the launch argument `gamemoderun %command%`, GameMode doesn't appear to be setting ioprio. It claims that it cannot 'inspect tasks for client'

However this also happens with a native game, which in this case gives the error of `Skipping ioprio on client [6372,6415]: ioprio was (4) but we expected (0)`

_Logs (systemctl status):_
_Log 1 (While Arma 3 is running):_

`desktop /usr/bin/gamemoded[832]: Adding game: 5944 [/home/telans/.local/share/Steam/steamapps/common/Arma 3/arma>`
`desktop /usr/bin/gamemoded[832]: Setting ioprio value...`
`desktop /usr/bin/gamemoded[832]: Removing expired game [5914]...`
`desktop /usr/bin/gamemoded[832]: Removing game: 5914 [/home/telans/.local/share/Steam/steamapps/compatdata/10741>`
`desktop /usr/bin/gamemoded[832]: Setting ioprio value...`
`desktop /usr/bin/gamemoded[832]: Could not inspect tasks for client [5914]! Skipping ioprio optimisation.`
`desktop /usr/bin/gamemoded[832]: Removing expired game [5911]...`
`desktop /usr/bin/gamemoded[832]: Removing game: 5911 [/home/telans/.local/share/Steam/steamapps/common/Proton 4.>`
`desktop /usr/bin/gamemoded[832]: Setting ioprio value...`
`desktop /usr/bin/gamemoded[832]: Could not inspect tasks for client [5911]! Skipping ioprio optimisation.`

_Log 2 (After Arma 3 has been closed):_

`desktop /usr/bin/gamemoded[832]: Setting ioprio value...`
`desktop /usr/bin/gamemoded[832]: Could not inspect tasks for client [5920]! Skipping ioprio optimisation.`
`desktop /usr/bin/gamemoded[832]: Removing expired game [5917]...`
`desktop /usr/bin/gamemoded[832]: Removing game: 5917 [/home/telans/.local/share/Steam/steamapps/compatdata/10741>`
`desktop /usr/bin/gamemoded[832]: Leaving Game Mode...`
`desktop /usr/bin/gamemoded[832]: Requesting update of governor policy to powersave`
`desktop pkexec[6045]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)`
`desktop /usr/bin/gamemoded[832]: Setting ioprio value...`
`desktop /usr/bin/gamemoded[832]: Could not inspect tasks for client [5917]! Skipping ioprio optimisation.`
`desktop /usr/bin/gamemoded[832]: Properly cleaned up all expired games.`

This also happens with other Proton games, also with a different error with native games.

**To Reproduce**

1. Run a Proton 4.11-1 game with `gamemoderun %command%`
2. Inspect `systemctl --user status gamemoded`
3. Notice errors of `Could not inspect tasks for client [5920]! Skipping ioprio optimisation.`
_________________________________________
1. Run a native game with `gamemoderun %command%`
2. Inspect `systemctl --user status gamemoded`
3. Notice errors of `Skipping ioprio on client [6372,6415]: ioprio was (4) but we expected (0).`

**Expected behavior**

`ioprio` to be set properly and not fail or skip.

**System Info (please complete the following information):**
 - OS and version: Arch Linux
 - GameMode Version: 1.4-git

Using default config

**Comment by edy-666** [comment]
I have the same problem using Ubuntu 18.04 LTS (tested with kernels 5.2.3 /  5.1 /  5.0 / 4.15 (official)) and GameMode version 1.4, Nvidia driver 430.40

Logs (systemctl status):
Log 1 (While Albion Online ''native game'' is running):

● gamemoded.service - gamemoded
   Loaded: loaded (/usr/lib/systemd/user/gamemoded.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-08-05 13:06:25 CEST; 22min ago
 Main PID: 1469 (gamemoded)
   Status: "GameMode is now active."
   CGroup: /user.slice/user-1000.slice/user@1000.service/gamemoded.service
           └─1469 /usr/bin/gamemoded -l

ago 05 13:28:37 edy666-Portatil /usr/bin/gamemoded[1469]: Removing game: 7786 [/bin/grep]
ago 05 13:28:37 edy666-Portatil /usr/bin/gamemoded[1469]: Setting ioprio value...
ago 05 13:28:40 edy666-Portatil /usr/bin/gamemoded[1469]: Removing expired game [7784]...
ago 05 13:28:40 edy666-Portatil /usr/bin/gamemoded[1469]: Removing game: 7784 [/bin/dash]
ago 05 13:28:40 edy666-Portatil /usr/bin/gamemoded[1469]: Setting ioprio value...
ago 05 13:28:40 edy666-Portatil /usr/bin/gamemoded[1469]: Could not inspect tasks for client [7784]! Skipping ioprio optimisation.
ago 05 13:28:40 edy666-Portatil /usr/bin/gamemoded[1469]: Removing expired game [7746]...
ago 05 13:28:40 edy666-Portatil /usr/bin/gamemoded[1469]: Removing game: 7746 [/bin/dash]
ago 05 13:28:40 edy666-Portatil /usr/bin/gamemoded[1469]: Setting ioprio value...
ago 05 13:28:40 edy666-Portatil /usr/bin/gamemoded[1469]: Could not inspect tasks for client [7746]! Skipping ioprio optimisation.

Log 2 (After Albion Online has been closed):

● gamemoded.service - gamemoded
   Loaded: loaded (/usr/lib/systemd/user/gamemoded.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-08-05 13:06:25 CEST; 23min ago
 Main PID: 1469 (gamemoded)
   Status: "GameMode is currently deactivated."
   CGroup: /user.slice/user-1000.slice/user@1000.service/gamemoded.service
           └─1469 /usr/bin/gamemoded -l

ago 05 13:29:09 edy666-Portatil /usr/bin/gamemoded[1469]: Skipping ioprio on client [7701,7783]: ioprio was (4) but we expected (0)
ago 05 13:29:09 edy666-Portatil /usr/bin/gamemoded[1469]: Skipping ioprio on client [7701,7794]: ioprio was (4) but we expected (0)
ago 05 13:29:12 edy666-Portatil /usr/bin/gamemoded[1469]: Removing expired game [7706]...
ago 05 13:29:12 edy666-Portatil /usr/bin/gamemoded[1469]: Removing game: 7706 [/home/edy666/.steam/steam/steamapps/common/Albion Online/launcher/QtWebEngineProcess]
ago 05 13:29:12 edy666-Portatil /usr/bin/gamemoded[1469]: Leaving Game Mode...
ago 05 13:29:12 edy666-Portatil /usr/bin/gamemoded[1469]: Requesting update of governor policy to powersave
ago 05 13:29:12 edy666-Portatil pkexec[7884]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
ago 05 13:29:12 edy666-Portatil /usr/bin/gamemoded[1469]: Setting ioprio value...
ago 05 13:29:12 edy666-Portatil /usr/bin/gamemoded[1469]: Could not inspect tasks for client [7706]! Skipping ioprio optimisation.
ago 05 13:29:12 edy666-Portatil /usr/bin/gamemoded[1469]: Properly cleaned up all expired games.

Log 3 (While Brawlhalla ''proton game'' is running):

● gamemoded.service - gamemoded
   Loaded: loaded (/usr/lib/systemd/user/gamemoded.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-08-05 13:06:25 CEST; 26min ago
 Main PID: 1469 (gamemoded)
   Status: "GameMode is now active."
   CGroup: /user.slice/user-1000.slice/user@1000.service/gamemoded.service
           └─1469 /usr/bin/gamemoded -l

ago 05 13:32:49 edy666-Portatil /usr/bin/gamemoded[1469]: Detected wine exe for client 8706 [C:\windows\system32\explorer.exe].
ago 05 13:32:49 edy666-Portatil /usr/bin/gamemoded[1469]: Detected wine prefix for client 8706: '/media/edy666/Data/steam2/steamapps/compatdata/291550/pfx/'
ago 05 13:32:49 edy666-Portatil /usr/bin/gamemoded[1469]: Successfully mapped wine client 8706 [/media/edy666/Data/steam2/steamapps/compatdata/291550/pfx/drive_c/windows/sys
ago 05 13:32:49 edy666-Portatil /usr/bin/gamemoded[1469]: Adding game: 8706 [/media/edy666/Data/steam2/steamapps/compatdata/291550/pfx/drive_c/windows/system32/explorer.exe]
ago 05 13:32:49 edy666-Portatil /usr/bin/gamemoded[1469]: Setting ioprio value...
ago 05 13:32:49 edy666-Portatil /usr/bin/gamemoded[1469]: Skipping ioprio on client [8706,8706]: ioprio was (0) but we expected (4)
ago 05 13:32:53 edy666-Portatil /usr/bin/gamemoded[1469]: Removing expired game [8679]...
ago 05 13:32:53 edy666-Portatil /usr/bin/gamemoded[1469]: Removing game: 8679 [/media/edy666/Data/steam2/steamapps/compatdata/291550/pfx/drive_c/windows/system32/wineboot.ex
ago 05 13:32:53 edy666-Portatil /usr/bin/gamemoded[1469]: Setting ioprio value...
ago 05 13:32:53 edy666-Portatil /usr/bin/gamemoded[1469]: Could not inspect tasks for client [8679]! Skipping ioprio optimisation.

**Comment by mdiluz** [comment]
I suspect this is a benign error, in both cases, gamemode is being injected into a subprocess which has a very short lifetime, so it's unable to set things up before the process dies. I suspect the rest is working fine.

There's likely something to be done here to assist in this situation - my current preference would be to shift into more of a "supervisor" focussed usage - where an external program is requesting gamemode on behalf of only the game process and nothing else. `LD_PRELOAD` was always a little brute force ;)

**Comment by zany130** [comment]
I also have this issue and it causes a mem leak in shadow of the tomb raider 

```
inxi -Fxxxza --no-host
System:    Kernel: 5.3.8-3-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0                                                
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.3-x86_64 root=UUID=d52056ad-8164-4fc0-be0c-f6ddfff48830 rw quiet 
           apparmor=1 security=apparmor udev.log_priority=3 
           Desktop: KDE Plasma 5.17.2 tk: Qt 5.13.1 info: latte-dock wm: kwin_x11 dm: SDDM Distro: Manjaro Linux 
Machine:   Type: Desktop System: Gigabyte product: X470 AORUS ULTRA GAMING v: N/A serial: <filter> 
           Mobo: Gigabyte model: X470 AORUS ULTRA GAMING-CF v: x.x serial: <filter> UEFI: American Megatrends v: F42a 
           date: 07/31/2019 
CPU:       Topology: 8-Core model: AMD Ryzen 7 2700X bits: 64 type: MT MCP arch: Zen+ family: 17 (23) model-id: 8 
           stepping: 2 microcode: 800820D L2 cache: 4096 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 118416 
           Speed: 3616 MHz min/max: 2200/3700 MHz boost: enabled Core speeds (MHz): 1: 4232 2: 2118 3: 2118 4: 2117 
           5: 2121 6: 4241 7: 2121 8: 4241 9: 2121 10: 2124 11: 2121 12: 4241 13: 2119 14: 4247 15: 4140 16: 2042 
           Vulnerabilities: Type: l1tf status: Not affected 
           Type: mds status: Not affected 
           Type: meltdown status: Not affected 
           Type: spec_store_bypass mitigation: Speculative Store Bypass disabled via prctl and seccomp 
           Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization 
           Type: spectre_v2 mitigation: Full AMD retpoline, IBPB: conditional, STIBP: disabled, RSB filling 
Graphics:  Device-1: NVIDIA GP104 [GeForce GTX 1080] vendor: Gigabyte driver: nvidia v: 440.26 bus ID: 0a:00.0 
           chip ID: 10de:1b80 
           Display: x11 server: X.Org 1.20.5 driver: nvidia compositor: kwin_x11 tty: N/A 
           OpenGL: renderer: GeForce GTX 1080/PCIe/SSE2 v: 4.6.0 NVIDIA 440.26 direct render: Yes 
Audio:     Device-1: NVIDIA GP104 High Definition Audio vendor: Gigabyte driver: snd_hda_intel v: kernel 
           bus ID: 0a:00.1 chip ID: 10de:10f0 
           Device-2: Advanced Micro Devices [AMD] Family 17h HD Audio vendor: Gigabyte driver: snd_hda_intel 
           v: kernel bus ID: 0c:00.3 chip ID: 1022:1457 
           Device-3: ASTRO Gaming ASTRO C40 type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 5-1:5 
           chip ID: 9886:0025 serial: <filter> 
           Device-4: Logitech G933 Wireless Headset Dongle type: USB driver: hid-generic,snd-usb-audio,usbhid 
           bus ID: 5-4:3 chip ID: 046d:0a5b 
           Sound Server: ALSA v: k5.3.8-3-MANJARO 
Network:   Device-1: Intel I211 Gigabit Network vendor: Gigabyte driver: igb v: 5.6.0-k port: f000 bus ID: 07:00.0 
           chip ID: 8086:1539 
           IF: enp7s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 2.96 TiB used: 1.99 TiB (67.1%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO 250GB size: 232.89 GiB block size: physical: 512 B 
           logical: 512 B speed: 31.6 Gb/s lanes: 4 serial: <filter> rev: 2B2QEXE7 scheme: GPT 
           ID-2: /dev/nvme1n1 vendor: Samsung model: SSD 960 EVO 250GB size: 232.89 GiB block size: physical: 512 B 
           logical: 512 B speed: 31.6 Gb/s lanes: 4 serial: <filter> rev: 3B7QCXE7 scheme: GPT 
           ID-3: /dev/sda vendor: Seagate model: ST2000DX002-2DV164 size: 1.82 TiB block size: physical: 4096 B 
           logical: 512 B speed: 6.0 Gb/s rotation: 7200 rpm serial: <filter> rev: CC41 
           ID-4: /dev/sdb vendor: Seagate model: ST1000DM010-2EP102 size: 931.51 GiB block size: physical: 4096 B 
           logical: 512 B speed: 6.0 Gb/s rotation: 7200 rpm serial: <filter> rev: CC43 scheme: GPT 
Partition: ID-1: / raw size: 232.59 GiB size: 227.94 GiB (98.00%) used: 186.97 GiB (82.0%) fs: ext4 
           dev: /dev/nvme0n1p2 
Sensors:   System Temperatures: cpu: 50.5 C mobo: N/A gpu: nvidia temp: 50 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 22% 
Info:      Processes: 479 Uptime: 14m Memory: 15.65 GiB used: 9.78 GiB (62.5%) Init: systemd v: 242 Compilers: 
           gcc: 9.2.0 alt: 8 clang: 9.0.0 Shell: bash v: 5.0.11 running in: cool-retro-term inxi: 3.0.36 
```

**Comment by GreatBigWhiteWorld** [comment]
Same errors as well. Thinking to turn this feature off, as I actually don't feel a difference?

**Comment by santi-andracchi** [comment]
Hi There! I have exactly the same issue running for CS GO on Manjaro, AMD Radeon 5 2500u Vega mobile 8.

**Comment by frostworx** [comment]
the gamemode package on arch and probably also manjaro comes with a 
`/etc/security/limits.d/10-gamemode.conf`
containing
`@gamemode - nice -10`

systemd comes with its own limits replacement in `/etc/systemd/user.conf`
so on some distros (at least arch/manjaro) per default `/etc/security/limits*` is ignored.
the "systemd-correct-way" would be to set that nice level somewhere in `/etc/systemd/user.conf`.
haven't checked how to set it per specific user and tbh I don't care.
the "backwards-compatible" way is to **enable pam_limits.so in /etc/pam.d/su**
I added 
`session              required        pam_limits.so`
at the end of `/etc/pam.d/su`
and the error is gone (after a reboot)

https://github.com/FeralInteractive/gamemode/issues/187 (duplicate?)
is probably fixed the same way
good luck!
