### ISSUE TITLE
Question: can 64-bit gamemode be used for 32-bit games?

### ISSUE THREAD

**Issue by connectety** [FeralInteractive/gamemode#252]
I am currently looking into fixing lutris gamemode support on ubuntu systems.
But because ubuntu only provides 64-bit binaries and self built gamemode works, i don't know if I should fix it.

**Comment by lucifertdark** [comment]
Although I'm not part of the development team, I can say that I have yet to find any game in my collection of 2500+ games that it doesn't work with.

**Comment by mdiluz** [comment]
Short answer: yes
Long answer (which is kind of important here): There are two parts of GameMode, the Daemon (`gamemoded`) and a dynamic library used to request GameMode (`libgamemode` or `libgamemodeauto`).

The Daemon should be installed on the system using the system architecture (ie. 64bit if you've installed a 64bit OS) and you only need that architecture installed.

To use `libgamemodeauto`, which is used by `gamemoderun` you need to have it built matching the same architecture as the game, so you'll want to have both if you're using that. The same applies to direct usage of `libgamemode`, which brings me to...

If you're looking to upgrade how Lutris uses GameMode, I'd recommend helping it to use the supervisor APIs found here: https://github.com/FeralInteractive/gamemode/blob/master/lib/gamemode_client.h#L54

Then, Lutris can request GameMode for a game it's launched directly with the daemon, and the architecture won't matter at all.

**Comment by stephanlachnit** [comment]
> I am currently looking into fixing lutris gamemode support on ubuntu systems.

Honestly it's kinda hilarious, Ubuntu broke this support by putting gamemode into main. Let me explain:
As mdiluz already mentioned, you need the 32bit library installed for 32bit, `gamemoderun` calls the library path depending on the executable.
Before Multi-Arch was a thing, you had packages like `libgamemode32` on amd64 but that's a total mess. Debian/Ubuntu came up with a solution called Mutli-Arch, which let's you install libraries for any architecture on your system, most notably i386 ("32bit") libraries on an amd ("64bit") installation (sadly I didn't get adopted by the FHS).
I wired up Multi-Arch for Debian, so one can install the 32bit library with `sudo apt install libgamemode:i386`. But Ubuntu stopped importing gamemode from Debian since they want to put it into their main repository (instead of universe), however they don't want to include one of the dependencies (inih). This lead to the situation that the gamemode package in Ubuntu lacks the new Mutli-Arch patches I provided. So honestly, there's nothing you can do, except hoping that they will eventually drop it from main (unlikely) _or_ put inih in main as well and start again importing the package from Debian (more likely, I heard one of the Canonical devs talking about this).

Alternatively, you can install the .deb's by hand from Debian, that should work: https://packages.debian.org/sid/i386/libgamemodeauto0/download & https://packages.debian.org/sid/i386/libgamemode0/download

> But because ubuntu only provides 32-bit binaries

you mean 64bit?

**Comment by stephanlachnit** [comment]
Just for reference, I opened a ticket on Launchpad to address 32bit support on Ubuntu: https://bugs.launchpad.net/ubuntu/+source/gamemode/+bug/1883253
On Debian `apt-get install gamemode` will now also install the 32bit libs if 32bit is enabled in dpkg, I guess this will be adopted for Ubuntu in 20.10 (groovy).

**Comment by mdiluz** [comment]
Very groovy indeed, thanks Stephan

**Comment by connectety** [comment]
I'll close this Question, because it has been answered for some time now.
Also there has been made a [change in lutris](https://github.com/lutris/lutris/commit/6dc584f78b2ccee4839ebbe3c51a1aee2bb28858) which makes it work and hopefully ubuntu will fix their part of the problem thanks to stephanlachnit.

**Comment by stephanlachnit** [comment]
> Also there has been made a change in lutris which makes it work and hopefully ubuntu will fix their part of the problem thanks to stephanlachnit.

They already did thanks to @seb128 :)
