### ISSUE TITLE
Automatic CPU Pinning for AMD 3D V-cache CPUs

### ISSUE THREAD

**Issue by CorvetteCole** [FeralInteractive/gamemode#412]
**Is your feature request related to a problem? Please describe.**
On the new AMD Ryzen 7950X3D, 3D cache is only available on one of the 8-core CCDs. This CCD is optimal for gaming because of this, and pinning a game process to it results in better performance. On Windows, the Ryzen drivers "park" non-3D cores when playing games, but such a functionality is not implemented in Linux (yet?) and it is relatively trivial to implement.

**Describe the solution you'd like**
If the user is running an AMD Ryzen 7950X3D or 7900X3D, pin the game process to only cores on the CCD containing 3D cache.

**Describe alternatives you've considered**
This doesn't have to be done in gamemoderun, and is perfectly easy to do separately. However, it seems like it might be a good fit for integration in general.

**Comment by HenrikHolst** [comment]
Actually I think parking the cores are easier than pinning, looked briefly at the logs when i ran a proton game and gamemode never once logged the pid of the actual game so looks like it at the moment cannot find the actual process for e.g wine/proton games (which would be the majority of games).

Btw do you happen to have a 7950x3d? I'm asking because I would like to know if it would be possible to detect the only-one-ccd-have-extra-cache so would like to get my hands on output from /sys/ from some one that does have this kind of cpu. I have only the 3800x3d myself but that is single ccd so I cannot do anything with it for this purpose.

**Comment by CorvetteCole** [comment]
I don't have a 7950X3D (yet). I understand that parking is easy, but it would be so much more beneficial if we could figure out how to pin a game to the 3D cache cores.

Part of the appeal to me is still having that whole other 8 core CCU to offload other background things off to. Parking would be a non-starter for me tbh, but doesn't mean it is a bad idea. I'll look into it

**Comment by HenrikHolst** [comment]
I agree with you in theory, however there is also the case that the other cores does share the L3 so even with pinning the CCD with the local L3 have to sometimes stall in order to send/receive data from the other CCD.

However the major issue is finding out the pid of the game process and it's threads. I did some tests and for many Linux native games and games launched with Lutris, gamemode found the real pid but when launched from Steam for many proton games it only found /usr/bin/env and never the actual game process. So even things like renice doesn't work correctly at the moment for proton games.

**Comment by CorvetteCole** [comment]
Yeah, getting the PID is the major challenge. Otherwise, I think you could even basically separate the CCUs entirely by setting the process affinity for all "other" processes to the other CCU and only the game to the 3D CCU. 

I've got a few ideas for how to find the PID automatically, but it may not end up being a good fit for gamemode, maybe a separate small utility.

It would be possible to launch Steam with some wrapper which would set the core affinity of Steam and any future children to the CCU with L3. Might not be ideal from a theoretical perspective but would sidestep the PID issue.

**Comment by CorvetteCole** [comment]
From a completely unrelated perspective, I wonder about the feasibility of a daemon which gathers heuristics on process cache usage and hit rate, then combined with CPU usage of that process can dynamically pin processes to the CCU with L3. Might give that a shot

**Comment by HenrikHolst** [comment]
Giving Steam a process mask of only one of the CCD:s would be the easier option yes, however that would then mean that e.g shader compilations with e.g pressure vessel would be locked out of half of the cores and I think that would increase the time to build the shaders quite a lot, but I have no data.

**Comment by HenrikHolst** [comment]
Then of course, core parking would also be a problem for the shader compilations so best would be to be able to have a reliable way to find the pid of the actual game. 

Another benefit of core parking is that power need should decrease so higher chance for the CCD with the cache to reach boost. Also according to other tests that I've seen with games this is not only for the x3d models since having a game threads running on multiple CCD:s is also problematic so even for the base 7950x core parking / thread pinning should be beneficial.

**Comment by CorvetteCole** [comment]
I think generally the scheduler is pretty aware of the desire to keep a process on a single CCD though. Would be nice to get some data on this

**Comment by HenrikHolst** [comment]
I don't think the scheduler is that clever yet, but of course it could be made to be this clever. The reason for this is that I have seen reports from people experiencing better game performance when they have disabled the other CCD: [https://github.com/FeralInteractive/gamemode/issues/55](url) , granted that was from 2018 so things might have been improved since then.

**Comment by okonech** [comment]
What kind of output specifically are you looking for @HenrikHolst? I have a 7950x3d and am running endeavouros. I'd love to see this feature so I'm willing to provide any logs you need :)

**Comment by HenrikHolst** [comment]
> What kind of output specifically are you looking for @HenrikHolst? I have a 7950x3d and am running endeavouros. I'd love to see this feature so I'm willing to provide any logs you need :)

Output from something like
`for f in /sys/devices/system/cpu/*/cache/*/* ; do echo $f; cat $f ; done`

Would be interesting, the key is to see if there is any way to automatically detect that some cores have access to more L3 than the others so a feature like this could be done with automation.

**Comment by okonech** [comment]
Sure thing, here you go:
[cpu-out.txt](https://github.com/FeralInteractive/gamemode/files/11368516/cpu-out.txt)

**Comment by HenrikHolst** [comment]
> Sure thing, here you go: [cpu-out.txt](https://github.com/FeralInteractive/gamemode/files/11368516/cpu-out.txt)

thanks, possible to also do a "lscpu -e" ?

**Comment by okonech** [comment]
Yup!
[lscpu-out.txt](https://github.com/FeralInteractive/gamemode/files/11368564/lscpu-out.txt)

**Comment by HenrikHolst** [comment]
> Yup! [lscpu-out.txt](https://github.com/FeralInteractive/gamemode/files/11368564/lscpu-out.txt)

Ok this is actually looking quite good. The /sys/devices/system/cpu/cpu*/cache/index3/size changes from 32MiB to 96MiB on CPU:s (8-15,24-31) and (0-7,16-23). Going by the lscpu output I assume here that 16-23 is the hyperthreaded siblings to 0-7 so by looking at these variables it should be possible to detect that 1) the cpu is having a non-uniform L3 cache and that the 8-15 and 24-31 cores should be parked to force everything to run on the cores with the higher L3 caches.

I'll see what I can do with this unless some one else beats me to it.

**Comment by HenrikHolst** [comment]
Ok so made a first test version that should properly autodetect that the L3 cache is non-uniform on say the 7950x3d and also detect which cores have the larger L3 and then try to park the other cores.

Now since parking the cores is a privileged operation this needs root so I've also written a small helper utility just like how cpu governor is set with and it _should_ work, I just have an issue with how to get pkexec to work with gamemode (the cpu governor helper fails on my system as well right now so the issue I have is local to my system I believe and not to this patch).

I'll create a full fork of the project later to be able to upload a full PR (not so accustomed to working with git or github) but until then the current patch is attached here:

[coreparking_patch.txt](https://github.com/FeralInteractive/gamemode/files/11378488/coreparking_patch.txt)

**Comment by HenrikHolst** [comment]
I have now also added the possibility to pin the threads instead of just parking the unwanted cores. Pinning is a bit more "loose" since a game can unpin at any moment while parking removes cores from the system while the game is running (and requires root privileges). Either can be enabled or disabled in a config file and pinning have precedence over parking. 

The current autodetect can only detect 7900x3d and 7950x3d at the moment but which cores to park or pin can also be set manually in the config. Should be possible to also add Intel e- and p-cores since they should be easily detectable as well.

Current patches can be seen here: [https://github.com/FeralInteractive/gamemode/compare/master...HenrikHolst:gamemode:master](url) and I will try to make a PR later unless some flagrant issues arises.

**Comment by CorvetteCole** [comment]
Very nice, you work much faster than I do!

**Comment by afayaz-feral** [comment]
I think we can consider this closed now that #416 is merged.

Thank you @HenrikHolst!
